import "./globals.css";

import { Montserrat } from "next/font/google";
import Providres from "./providers/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providres>
        <body className={`${montserrat.className} min-h-screen`}>
          {children}
        </body>
      </Providres>
    </html>
  );
}
