import "./globals.css";
import Providers from "./providers";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${montserrat.className} min-h-screen`}>
          {children}
        </body>
      </Providers>
    </html>
  );
}
