import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`min-h-screen antialiased`}>{children}</body>
      </Providers>
    </html>
  );
}
